### ISSUE TITLE
memory leaks in getgb2s()

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#406]
If getgb2s() is run the following way, there is a memory leak:

```
=================================================================
5: ==8778==ERROR: LeakSanitizer: detected memory leaks
5: 
5: Direct leak of 35724 byte(s) in 687 object(s) allocated from:
5:     #0 0x7fcba2698867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
5:     #1 0x5622dd8e41dc in gf_unpack1_ /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/src/gf_unpack1.f:73
5:     #2 0x5622dd8df9f0 in getgb2s_ /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/src/getgb2s.f:140
5:     #3 0x5622dd8c2bab in test_getgb2s /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/tests/test_getgb2s.F90:157
5:     #4 0x5622dd8c319e in main /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/tests/test_getgb2s.F90:7
5:     #5 0x7fcba1e6cd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
5: 
5: SUMMARY: AddressSanitizer: 35724 byte(s) leaked in 687 allocation(s).
 5/72 Test  #5: test_getgb2s_4 ...................***Failed    0.50 sec

```
This happens when we specify a section 4 value to match, and it is not matched. In that case the following code is called:

```
        IF ( .NOT. MATCH3 ) THEN
           IF (ASSOCIATED(GFLD%IGDTMPL)) DEALLOCATE(GFLD%IGDTMPL)
           IF (ASSOCIATED(GFLD%LIST_OPT)) DEALLOCATE(GFLD%LIST_OPT)
           IPOS=IPOS+INLEN
           CYCLE

```
The problem here is that GFDL%IDSECT has also been allocated by this time. If not freed, then it leaks.

This can be solved by adding:

`           IF (ASSOCIATED(GFLD%IDSECT)) DEALLOCATE(GFLD%IDSECT)
`

**Comment by edwardhartnett** [comment]
There's another memory leak as well, which occurs when we try and select for a PDT value that is not present:

```
=================================================================
5: ==8693==ERROR: LeakSanitizer: detected memory leaks
5: 
5: Direct leak of 35724 byte(s) in 687 object(s) allocated from:
5:     #0 0x7f2a25430867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
5:     #1 0x562797299e79 in gf_unpack1_ /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/src/gf_unpack1.f:73
5:     #2 0x562797295787 in getgb2s_ /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/src/getgb2s.f:140
5:     #3 0x562797278942 in test_getgb2s /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/tests/test_getgb2s.F90:157
5:     #4 0x562797278f35 in main /home/runner/work/NCEPLIBS-g2/NCEPLIBS-g2/g2/tests/test_getgb2s.F90:7
5:     #5 0x7f2a24c04d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
5: 
5: SUMMARY: AddressSanitizer: 35724 byte(s) leaked in 687 allocation(s).

```
This is due to this code:
```
        IF ( .NOT. MATCH4 ) THEN
           IF (ASSOCIATED(GFLD%IPDTMPL)) DEALLOCATE(GFLD%IPDTMPL)
           IF (ASSOCIATED(GFLD%COORD_LIST)) DEALLOCATE(GFLD%COORD_LIST)
        ENDIF

```
Which also needs to free GFLD%IDSECT.
