### ISSUE TITLE
memory problem in test_getgb2 when Debug build is not used

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#434]
When I turn off Debug I get a memory problem:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

```
Backtrace for this error:
#0  0x7fc693728700 in ???
#1  0x7fc6937278a5 in ???
#2  0x7fc6933c008f in ???
	at /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x558b36bef33c in putgb2_
	at /home/ed/NCEPLIBS-g2/src/putgb2.F90:151
#4  0x558b36bcd173 in test_getgb2
	at /home/ed/NCEPLIBS-g2/tests/test_getgb2.F90:119
#5  0x558b36bcb4ce in main
	at /home/ed/NCEPLIBS-g2/tests/test_getgb2.F90:8
Segmentation fault (core dumped)

```

**Comment by edwardhartnett** [comment]
This has been fixed, it was a test issue.
