### ISSUE TITLE
jasper issue when running utility in run_copygb2_tests.sh

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2#789]
```
+ ../utils/copygb2 -g '30 6 0 0 0 0 0 0 1473 1025 12190000 226541000 8 25000000 265000000 5079000 5079000 0 64 25000000 25000000' '-i1 1' -x data/ref_gdaswave.t00z.wcoast.0p16.f000.grib2 test_gdaswave_2.ip.grib2
maximum memory limit (10000000) would be exceeded
cannot encode main body
jpc_encode failed
copygb2: /home/ed/Downloads/jasper-4.0.0/src/libjasper/base/jas_init.c:505: jas_init_library: Assertion `!jas_global.initialized' failed.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7bfed2a23e59 in ???
#1  0x7bfed2a22e75 in ???
#2  0x7bfed1e4531f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7bfed1e9eb1c in __pthread_kill_implementation
	at ./nptl/pthread_kill.c:44
#4  0x7bfed1e9eb1c in __pthread_kill_internal
	at ./nptl/pthread_kill.c:78
#5  0x7bfed1e9eb1c in __GI___pthread_kill
	at ./nptl/pthread_kill.c:89
#6  0x7bfed1e4526d in __GI_raise
	at ../sysdeps/posix/raise.c:26
#7  0x7bfed1e288fe in __GI_abort
	at ./stdlib/abort.c:79
#8  0x7bfed1e2881a in __assert_fail_base
	at ./assert/assert.c:94
#9  0x7bfed1e3b506 in __assert_fail
	at ./assert/assert.c:103
#10  0x7bfed2d7009c in jas_init_library
	at /home/ed/Downloads/jasper-4.0.0/src/libjasper/base/jas_init.c:505
#11  0x7bfed2f58260 in enc_jpeg2000
	at /home/ed/NCEPLIBS-g2c/src/decenc_jpeg2000.c:150
#12  0x7bfed2f5919a in jpcpack_int
	at /home/ed/NCEPLIBS-g2c/src/jpcpack.c:193
#13  0x7bfed2f5951d in g2c_jpcpackd
	at /home/ed/NCEPLIBS-g2c/src/jpcpack.c:396
#14  0x56da90c428f0 in jpcpack_
	at /home/ed/NCEPLIBS-g2/src/g2jpc.F90:74
#15  0x56da90c3fdff in addfield_
	at /home/ed/NCEPLIBS-g2/src/g2create.F90:489
#16  0x56da90c38883 in putgb2_
	at /home/ed/NCEPLIBS-g2/src/g2gf.F90:130
#17  0x56da90c2e5b6 in cpgb1
	at /home/ed/NCEPLIBS-g2/utils/copygb2.F90:1158
#18  0x56da90c2fb30 in cpgb
	at /home/ed/NCEPLIBS-g2/utils/copygb2.F90:719
#19  0x56da90c28ce8 in copygb2
	at /home/ed/NCEPLIBS-g2/utils/copygb2.F90:523
#20  0x56da90c30440 in main
	at /home/ed/NCEPLIBS-g2/utils/copygb2.F90:524
./run_copygb2_tests.sh: line 17: 242306 Aborted                 (core dumped) ../utils/copygb2 -g "30 6 0 0 0 0 0 0 1473 1025 12190000 226541000 8 25000000 265000000 5079000 5079000 0 64 25000000 25000000" -i"1 1" -x data/ref_gdaswave.t00z.wcoast.0p16.f000.grib2 test_gdaswave_2.ip.grib2
```

**Comment by edwardhartnett** [comment]
This went away after I increased the memory for jasper in g2c. However, this requires g2c-2.1.0.
